app = 'jir-blazor'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile.blazor'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://0.0.0.0:8080'
  ApiBaseUrl = 'https://jir.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
