[phases.setup]
nixPkgs = ['...', 'dotnet-sdk_9']

[phases.build]
cmds = [
  'dotnet restore src/JIR.WebAPI/JIR.WebAPI.csproj',
  'dotnet publish src/JIR.WebAPI/JIR.WebAPI.csproj -c Release -o /app/publish'
]

[start]
cmd = 'dotnet /app/publish/JIR.WebAPI.dll'
