// <auto-generated />
using System;
using JIR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JIR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117174142_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JIR.Domain.Entities.ArticleMagasin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code_article");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("designation");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MagasinId")
                        .HasColumnType("uuid")
                        .HasColumnName("magasin_id");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("prix_unitaire");

                    b.Property<decimal>("QuantiteStock")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("quantite_stock");

                    b.Property<decimal>("SeuilAlerte")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("seuil_alerte");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unite");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MagasinId", "CodeArticle")
                        .IsUnique()
                        .HasDatabaseName("i_x_articles_magasin_magasin_id_code_article");

                    b.ToTable("articles_magasin");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Cotisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MembreMatricule")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("membre_matricule");

                    b.Property<string>("MembreNom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("membre_nom");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode_paiement");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("periode");

                    b.Property<string>("RecuNumero")
                        .HasColumnType("text")
                        .HasColumnName("recu_numero");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statut");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("i_x_cotisations_section_id");

                    b.ToTable("cotisations");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Depense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beneficiaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiaire");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categorie");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateDepense")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_depense");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<DateTime?>("DateValidation1")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_validation1");

                    b.Property<DateTime?>("DateValidation2")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_validation2");

                    b.Property<Guid>("DemandeurId")
                        .HasColumnType("uuid")
                        .HasColumnName("demandeur_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("libelle");

                    b.Property<string>("ModePaiement")
                        .HasColumnType("text")
                        .HasColumnName("mode_paiement");

                    b.Property<decimal>("Montant")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("montant");

                    b.Property<string>("NumeroDocument")
                        .HasColumnType("text")
                        .HasColumnName("numero_document");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("PieceJustificative")
                        .HasColumnType("text")
                        .HasColumnName("piece_justificative");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<int>("StatutWorkflow")
                        .HasColumnType("integer")
                        .HasColumnName("statut_workflow");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("Validateur1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("validateur1_id");

                    b.Property<Guid?>("Validateur2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("validateur2_id");

                    b.HasKey("Id");

                    b.HasIndex("DemandeurId")
                        .HasDatabaseName("i_x_depenses_demandeur_id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("i_x_depenses_section_id");

                    b.HasIndex("Validateur1Id")
                        .HasDatabaseName("i_x_depenses_validateur1_id");

                    b.HasIndex("Validateur2Id")
                        .HasDatabaseName("i_x_depenses_validateur2_id");

                    b.ToTable("depenses");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Magasin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Localisation")
                        .HasColumnType("text")
                        .HasColumnName("localisation");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_magasins_code");

                    b.HasIndex("ResponsableId")
                        .HasDatabaseName("i_x_magasins_responsable_id");

                    b.ToTable("magasins");
                });

            modelBuilder.Entity("JIR.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_mouvement");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Motif")
                        .HasColumnType("text")
                        .HasColumnName("motif");

                    b.Property<string>("NumeroDocument")
                        .HasColumnType("text")
                        .HasColumnName("numero_document");

                    b.Property<decimal>("Quantite")
                        .HasColumnType("numeric")
                        .HasColumnName("quantite");

                    b.Property<int>("TypeMouvement")
                        .HasColumnType("integer")
                        .HasColumnName("type_mouvement");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("i_x_mouvements_stock_article_id");

                    b.ToTable("mouvements_stock");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Partenaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ContactNom")
                        .HasColumnType("text")
                        .HasColumnName("contact_nom");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActif")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actif");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nom");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("Telephone")
                        .HasColumnType("text")
                        .HasColumnName("telephone");

                    b.Property<int>("TypePartenaire")
                        .HasColumnType("integer")
                        .HasColumnName("type_partenaire");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("partenaires");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Recette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categorie");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateRecette")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_recette");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("libelle");

                    b.Property<string>("ModeEncaissement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mode_encaissement");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric")
                        .HasColumnName("montant");

                    b.Property<string>("NumeroDocument")
                        .HasColumnType("text")
                        .HasColumnName("numero_document");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("PieceJustificative")
                        .HasColumnType("text")
                        .HasColumnName("piece_justificative");

                    b.Property<string>("RecuNumero")
                        .HasColumnType("text")
                        .HasColumnName("recu_numero");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("i_x_recettes_section_id");

                    b.ToTable("recettes");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BudgetAnnuel")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("budget_annuel");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_sections_code");

                    b.HasIndex("ResponsableId")
                        .HasDatabaseName("i_x_sections_responsable_id");

                    b.ToTable("sections");
                });

            modelBuilder.Entity("JIR.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("i_x_users_section_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("JIR.Domain.Entities.ArticleMagasin", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Magasin", "Magasin")
                        .WithMany("Articles")
                        .HasForeignKey("MagasinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_articles_magasin__magasins_magasin_id");

                    b.Navigation("Magasin");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Cotisation", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Cotisations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_cotisations__sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Depense", b =>
                {
                    b.HasOne("JIR.Domain.Entities.User", "Demandeur")
                        .WithMany("Depenses")
                        .HasForeignKey("DemandeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_depenses__users_demandeur_id");

                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Depenses")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_depenses__sections_section_id");

                    b.HasOne("JIR.Domain.Entities.User", "Validateur1")
                        .WithMany("ValidatedDepenses1")
                        .HasForeignKey("Validateur1Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_depenses__users_validateur1_id");

                    b.HasOne("JIR.Domain.Entities.User", "Validateur2")
                        .WithMany("ValidatedDepenses2")
                        .HasForeignKey("Validateur2Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_depenses__users_validateur2_id");

                    b.Navigation("Demandeur");

                    b.Navigation("Section");

                    b.Navigation("Validateur1");

                    b.Navigation("Validateur2");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Magasin", b =>
                {
                    b.HasOne("JIR.Domain.Entities.User", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .HasConstraintName("f_k_magasins__users_responsable_id");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("JIR.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("JIR.Domain.Entities.ArticleMagasin", "Article")
                        .WithMany("Mouvements")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_mouvements_stock_articles_magasin_article_id");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Recette", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Recettes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_recettes__sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Section", b =>
                {
                    b.HasOne("JIR.Domain.Entities.User", "Responsable")
                        .WithMany("ManagedSections")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_sections__users_responsable_id");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("JIR.Domain.Entities.User", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Members")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_users_sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.ArticleMagasin", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Magasin", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Section", b =>
                {
                    b.Navigation("Cotisations");

                    b.Navigation("Depenses");

                    b.Navigation("Members");

                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("JIR.Domain.Entities.User", b =>
                {
                    b.Navigation("Depenses");

                    b.Navigation("ManagedSections");

                    b.Navigation("ValidatedDepenses1");

                    b.Navigation("ValidatedDepenses2");
                });
#pragma warning restore 612, 618
        }
    }
}
