// <auto-generated />
using System;
using JIR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JIR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JIR.Domain.Entities.ArticleMagasin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code_article");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("designation");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MagasinId")
                        .HasColumnType("uuid")
                        .HasColumnName("magasin_id");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observations");

                    b.Property<decimal>("PrixUnitaire")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("prix_unitaire");

                    b.Property<decimal>("QuantiteStock")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantite_stock");

                    b.Property<decimal>("SeuilAlerte")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("seuil_alerte");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unite");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_articles_magasin_is_deleted");

                    b.HasIndex("MagasinId", "CodeArticle")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_magasin_magasin_code");

                    b.ToTable("articles_magasin", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.Cotisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MembreMatricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("membre_matricule");

                    b.Property<string>("MembreNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("membre_nom");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode_paiement");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("montant");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observations");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periode");

                    b.Property<string>("RecuNumero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recu_numero");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DatePaiement")
                        .HasDatabaseName("ix_cotisations_date_paiement");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_cotisations_is_deleted");

                    b.HasIndex("Periode")
                        .HasDatabaseName("ix_cotisations_periode");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_cotisations_section_id");

                    b.ToTable("cotisations", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.Depense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beneficiaire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beneficiaire");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categorie");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateDepense")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_depense");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_paiement");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_validation");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode_paiement");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("montant");

                    b.Property<string>("MotifRejet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motif_rejet");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observations");

                    b.Property<string>("ReferenceFacture")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_facture");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("statut");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("valide_par");

                    b.HasKey("Id");

                    b.HasIndex("DateDepense")
                        .HasDatabaseName("ix_depenses_date_depense");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_depenses_is_deleted");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_depenses_numero");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_depenses_section_id");

                    b.HasIndex("Statut")
                        .HasDatabaseName("ix_depenses_statut");

                    b.ToTable("depenses", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.Magasin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Localisation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("localisation");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_magasins_code");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_magasins_is_deleted");

                    b.HasIndex("ResponsableId")
                        .HasDatabaseName("i_x_magasins_responsable_id");

                    b.ToTable("magasins", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_mouvement");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Motif")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motif");

                    b.Property<string>("NumeroDocument")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_document");

                    b.Property<decimal>("Quantite")
                        .HasPrecision(15, 3)
                        .HasColumnType("numeric(15,3)")
                        .HasColumnName("quantite");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_mouvement");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_mouvements_stock_article_id");

                    b.HasIndex("DateMouvement")
                        .HasDatabaseName("ix_mouvements_stock_date_mouvement");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_mouvements_stock_is_deleted");

                    b.HasIndex("TypeMouvement")
                        .HasDatabaseName("ix_mouvements_stock_type_mouvement");

                    b.ToTable("mouvements_stock", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.Partenaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("adresse");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactNom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_nom");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_actif");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observations");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telephone");

                    b.Property<string>("TypePartenaire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type_partenaire");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_partenaires_code");

                    b.HasIndex("IsActif")
                        .HasDatabaseName("ix_partenaires_is_actif");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_partenaires_is_deleted");

                    b.HasIndex("TypePartenaire")
                        .HasDatabaseName("ix_partenaires_type");

                    b.ToTable("partenaires", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.Recette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categorie");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateRecette")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_recette");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("libelle");

                    b.Property<string>("ModeEncaissement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode_encaissement");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("montant");

                    b.Property<string>("NumeroDocument")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_document");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observations");

                    b.Property<string>("PieceJustificative")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("piece_justificative");

                    b.Property<string>("RecuNumero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recu_numero");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Categorie")
                        .HasDatabaseName("ix_recettes_categorie");

                    b.HasIndex("DateRecette")
                        .HasDatabaseName("ix_recettes_date_recette");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_recettes_is_deleted");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_recettes_section_id");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_recettes_source");

                    b.HasIndex("SectionId", "DateRecette")
                        .HasDatabaseName("ix_recettes_section_date");

                    b.ToTable("recettes", (string)null);
                });

            modelBuilder.Entity("JIR.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BudgetAnnuel")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("budget_annuel");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nom");

                    b.Property<Guid?>("ResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsable_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_sections_code");

                    b.HasIndex("ResponsableId")
                        .HasDatabaseName("i_x_sections_responsable_id");

                    b.ToTable("sections");
                });

            modelBuilder.Entity("JIR.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nom");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prenom");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("section_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("i_x_users_section_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username");

                    b.ToTable("users");
                });

            modelBuilder.Entity("JIR.Domain.Entities.ArticleMagasin", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Magasin", "Magasin")
                        .WithMany("Articles")
                        .HasForeignKey("MagasinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_articles_magasin_magasins_magasin_id");

                    b.Navigation("Magasin");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Cotisation", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Cotisations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_cotisations__sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Depense", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Depenses")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_depenses__sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Magasin", b =>
                {
                    b.HasOne("JIR.Domain.Entities.User", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_magasins__users_responsable_id");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("JIR.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("JIR.Domain.Entities.ArticleMagasin", "Article")
                        .WithMany("Mouvements")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_mouvements_stock_articles_magasin_article_id");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Recette", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Recettes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_recettes__sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Section", b =>
                {
                    b.HasOne("JIR.Domain.Entities.User", "Responsable")
                        .WithMany("ManagedSections")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_sections__users_responsable_id");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("JIR.Domain.Entities.User", b =>
                {
                    b.HasOne("JIR.Domain.Entities.Section", "Section")
                        .WithMany("Members")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_users_sections_section_id");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("JIR.Domain.Entities.ArticleMagasin", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Magasin", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("JIR.Domain.Entities.Section", b =>
                {
                    b.Navigation("Cotisations");

                    b.Navigation("Depenses");

                    b.Navigation("Members");

                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("JIR.Domain.Entities.User", b =>
                {
                    b.Navigation("ManagedSections");
                });
#pragma warning restore 612, 618
        }
    }
}
